### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by arnabkuw** [IDLabMedia/tgif-dataset#1]
Hello authors,

Out of all the download links provided in the repo (readme), I could only find Fake Images -> Adobe Firefly and Masks -> Photoshop masks, but all other links led me to an empty folder. Can you please clarify if the data is not available or I'm missing something?

**Comment by hmareen** [comment]
Thanks for notifying us, and sorry for our late response (I did not receive a notification).

The download link is now fixed (in commit [db3cb4c](https://github.com/IDLabMedia/tgif-dataset/commit/db3cb4cb0d3aedb73da950de8c9f672c527b818b))!
